name: flutter_rest_data_example
description: An example project to showcase flutter_rest_data package.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #TODO go back to relative path here when null safety improvements are merged
  flutter_rest_data:
    git:
      url: git://github.com/algonauti/flutter-rest-data.git
      ref: null-safety-improvements

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
